server:
  port: 8080
---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: jhj1234
      authentication-database: admin # 정상적인 MongoDB 접속을 위해 필요함
      database: reactive-web
  webflux:
    hiddenmethod:
      filter:
        enabled: true
---
logging:
  level:
    org.springframework.data: TRACE
---
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info

--- # 동작은 안함
info:
  project:
    version: @project.version@
  java:
    version: @java.version@
  spring:
    framework:
      version: @spring-framework.version@
    data:
      version: @spring-data-bom.version@