server:
  port: 8080
---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: jhj1234
      authentication-database: admin # 정상적인 MongoDB 접속을 위해 필요함
      database: reactive-web
  webflux:
    hiddenmethod:
      filter:
        enabled: true
---
logging:
  level:
    org.springframework.data: TRACE

